tap 'mscharley/homebrew'

cask '1password'
cask 'alfred'
cask 'bitbar'
cask 'fantastical'
cask 'firefox'
cask 'daisydisk'
cask 'docker'
cask 'keepingyouawake'
cask 'ngrok'
cask 'rectangle'
cask 'slack'
cask 'spotify'
cask 'typora'
cask 'viscosity'
cask 'whatsapp'
cask 'zoom'

brew 'awscli'
brew 'mscharley/homebrew/alacritty', args: ['HEAD']
brew 'coreutils'
brew 'fzf'
brew 'git'
brew 'git-delta'
brew 'go'
brew 'nodenv'
brew 'mas'
brew 'the_silver_searcher'
brew 'rust'
brew 'rbenv'
brew 'tmate'
brew 'tmux'
brew 'nvim'
