#!/bin/zsh

set -e

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

  echo "brew bundle"
  brew bundle --file Brewfile.linux
elif [[ "$OSTYPE" == "darwin"* ]]; then
  eval "$(/usr/local/bin/brew shellenv)"
  echo "macos defaults"
  defaults write com.apple.Dock tilesize -int 1
  defaults write com.apple.Dock autohide-delay -float 5
  killall Dock

  echo "brew bundle"
  brew bundle
fi

echo "brew post-install steps"
$(brew --prefix)/opt/fzf/install

echo "git submodule update"
git submodule init
git submodule update

pwd=$(pwd)

for f in $(find config -d 1) ; do
	ff=$(basename $f)
	echo "link $pwd/config/$ff -> $HOME/$ff"
	ln -Fs "$pwd/config/$ff" "$HOME"
done

source ~/.zshrc

echo "install language servers"
gem install solargraph
npm install -g javascript-typescript-langserver
npm install -g bash-language-server
go get golang.org/x/tools/gopls@latest
